version: '2'
services:
    thc-app:
        image: thc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://thc-mysql:3306/thc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    thc-mysql:
        extends:
            file: mysql.yml
            service: thc-mysql
